#__  ___  _______      _______ .______          ___      .___  ___.  ___________    __    ____  ______   .______       __  ___
#|  |/  / |       \    |   ____||   _  \        /   \     |   \/   | |   ____\   \  /  \  /   / /  __  \  |   _  \     |  |/  /
#|  '  /  |  .--.  |   |  |__   |  |_)  |      /  ^  \    |  \  /  | |  |__   \   \/    \/   / |  |  |  | |  |_)  |    |  '  /
#|    <   |  |  |  |   |   __|  |      /      /  /_\  \   |  |\/|  | |   __|   \            /  |  |  |  | |      /     |    <
#|  .  \  |  '--'  |   |  |     |  |\  \----./  _____  \  |  |  |  | |  |____   \    /\    /   |  `--'  | |  |\  \----.|  .  \
#|__|\__\ |_______/    |__|     | _| `._____/__/     \__\ |__|  |__| |_______|   \__/  \__/     \______/  | _| `._____||__|\__\
#
# Dont touch it if you dont know what your doing

general:
  settings:
    prefix: '&7&l(&2&lKD&7&l)'
    chats:
      public:
        prefix: '!'
        format: '&7[&aP&7]%kdf_land_prefix%%kdf_rank_prefix%%s &7➣ '
      roleplay:
        prefix: '#'
        format: '&7[&fRP&7]%kdf_land_prefix%%kdf_rank_prefix%%s &7➣ '
      kingdom:
        prefix: '@'
        format: '&7[&9KD&7]%kdf_rank_prefix%%s &7➣ '
        default: True
    world:
      name: "world"
      spawn-delay: 5
      spawn:
        x: 0
        y: 0
        z: 0
        yaw: 0.0
        pitch: 0.0
  messages:
    on-first: '&7&l(&2&l+&7&l) &2&l%player_displayname% &ais voor het eerst op de server!'
    on-join: '&7&l(&2&l+&7&l) %kdf_land_prefix% &2&l%player_displayname%'
    on-quit: '&7&l(&4&l-&7&l) %kdf_land_prefix% &2&l%player_displayname%'
    config-reload: '&aSuccesvol de &2&lConfiguratie &aherladen!'
    no-permission: '&cJe hebt hiervoor geen permissie'
  scoreboard:
    title: '&6&lVintage&e&lNetwork'
    ip: 'play.vintagenetwork.eu'
    color: '&6'