#__  ___  _______      _______ .______          ___      .___  ___.  ___________    __    ____  ______   .______       __  ___
#|  |/  / |       \    |   ____||   _  \        /   \     |   \/   | |   ____\   \  /  \  /   / /  __  \  |   _  \     |  |/  /
#|  '  /  |  .--.  |   |  |__   |  |_)  |      /  ^  \    |  \  /  | |  |__   \   \/    \/   / |  |  |  | |  |_)  |    |  '  /
#|    <   |  |  |  |   |   __|  |      /      /  /_\  \   |  |\/|  | |   __|   \            /  |  |  |  | |      /     |    <
#|  .  \  |  '--'  |   |  |     |  |\  \----./  _____  \  |  |  |  | |  |____   \    /\    /   |  `--'  | |  |\  \----.|  .  \
#|__|\__\ |_______/    |__|     | _| `._____/__/     \__\ |__|  |__| |_______|   \__/  \__/     \______/  | _| `._____||__|\__\
#
# Dont touch it if you dont know what your doing

land:
  invite: True
  maximum: 15
  icon: 'tent'
  ranks:
    Stamhoofd:
      level: 50
      maximum: 1
      prefix: "&7[&6Stamhoofd&7]"
      tab: '&7[&5â€&7]'
    Inwoner:
      level: 1
      default: true
      prefix: "&7[&8Inwoner&7]"